name: A workflow for my Hello World file
on: push # workflow will execute when code is "pushed" to the repo

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps: # linear sequence of ops that makes up a job
      - uses: actions/checkout@v1 # allow workflow to access contents of the repo
      - uses: ./action-a # relative path to the action
        with: # specify input vars that will be available to the action
          MY_NAME: "Badhreesh"